export const FETCH_CARDS_TYPE = 'FETCH_CARDS_TYPE';
export const FILTER_CARDS_TYPE = 'FILTER_CARDS_TYPE';
export const CREATE_CARD_TYPE = 'CREATE_CARD_TYPE';
export const UPDATE_CARD_TYPE = 'UPDATE_CARD_TYPE';
export const DELETE_CARD_TYPE = 'DELETE_CARD_TYPE';
